# A. REPRODUCIBLE NORMALIZATION PROBLEM

In [1]:
import numpy as np

In [2]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5)) 

In [3]:
X_normalized=(X-np.mean(X))/np.std(X)

In [4]:
np.mean(X_normalized)

np.float64(0.0)

In [5]:
np.std(X_normalized)

np.float64(0.9999999999999999)

## REQUIRED CHECKS

In [7]:
print ("X Array:\n", X, "\n")
print ("X_normalized Array:\n", X_normalized, "\n")
print ("X_normalized Mean:", np.mean(X_normalized), "\n")
print ("X_normalized Standard Deviation:", np.std(X_normalized))

X Array:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]] 

X_normalized Array:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]] 

X_normalized Mean: 0.0 

X_normalized Standard Deviation: 0.9999999999999999


In [8]:
np.save('X_normalized.npy', X_normalized)

# B. CUBES DIVISIBLE BY 4 PROBLEM

In [9]:
C=np.arange(1,101)**3
C.resize(10,10)

In [10]:
div_by_4=C[C%4==0]

## REQUIRED CHECKS

In [11]:
print ("Shape of C:", np.shape(C), "\n")
print ("div_by_4 Array:\n", div_by_4, "\n")
print ("Nummber of elements stored in div_by_4:", len(div_by_4))

Shape of C: (10, 10) 

div_by_4 Array:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000] 

Nummber of elements stored in div_by_4: 50


In [12]:
np.save('div_by_4.npy', div_by_4)

# C. ABOVE-MEAN SQUARES PROBLEM

In [13]:
S=np.arange(1,37)**2
S.resize(6,6)

In [14]:
S_mean=np.mean(S)

In [15]:
above_mean=S[S>S_mean]

## REQUIRED CHECKS

In [16]:
print ("S Array: \n", S, "\n")
print ("Mean of all elements in Array S:", S_mean, "\n")
print ("above_mean Array: ", above_mean, "\n")
print ("Number of elements stored in above_mean:", len(above_mean))

S Array: 
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]] 

Mean of all elements in Array S: 450.1666666666667 

above_mean Array:  [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296] 

Number of elements stored in above_mean: 15


In [17]:
np.save('above_mean.npy', above_mean)